#!/bin/bash
for file in *.html
do
  target_path="../$file"
  if [ -f "$target_path" ]
  then
    if [ "$file" -nt "$target_path" ]
    then
      # Copy the file to the parent directory
      cp "$file" "../$file"
    fi
  else
    cp "$file" "../$file"
  fi
done
